from src.domain.constants.scoring.aliases import Score

LEVEL_SCORE_WEIGHT: Score = 0.25
MARKET_SCORE_WEIGHT: Score = 0.20
CV_GAP_SCORE_WEIGHT: Score = 0.20
DIFFICULTY_SCORE_WEIGHT: Score = 0.15
DIVERSITY_SCORE_WEIGHT: Score = 0.15
FATIGUE_SCORE_WEIGHT: Score = 0.05

TOTAL_SCORE_WEIGHT: Score = (
    LEVEL_SCORE_WEIGHT
    + MARKET_SCORE_WEIGHT
    + CV_GAP_SCORE_WEIGHT
    + DIFFICULTY_SCORE_WEIGHT
    + DIVERSITY_SCORE_WEIGHT
    + FATIGUE_SCORE_WEIGHT
)